apiVersion: v1
kind: Service
metadata:
  name: baby-hexbatch
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: baby-hexbatch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baby-hexbatch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: baby-hexbatch
  template:
    metadata:
      labels:
        app: baby-hexbatch
    spec:
      containers:
      - name: baby-hexbatch
        image: registry.digitalocean.com/will-k8s/baby-hex
        ports:
        - containerPort: 80
